language: cpp
dist: bionic
compiler: gcc
<<<<<<< HEAD
dist: bionic
=======
>>>>>>> develop

install: 
  - sudo apt update -qq
  # valgrind
  - sudo apt-get install -qq valgrind

script: 
  - qmake
  - make
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./travis_qmake_gcc_cpp11_memcheck
  - cat memcheck.log